### ISSUE TITLE
Can't verify BB(6) champion

### ISSUE THREAD

**Issue by nickdrozd** [sligocki/busy-beaver#3]
With `Quick_Sim`, I can verify the BB(6) second-place program (`1RB 0LD  1RC 0RF  1LC 1LA  0LE 1LZ  1LA 0RB  0RC 0RE`) after just 1873 loops. But the first-place program (`1RB 1LE  1RC 1RF  1LD 0RB  1RE 0LC  1LA 0RD  1LZ 1RC`) I can't verify at all. Often the process gets killed.

Are there some particular settings that will make it work?

**Comment by sligocki** [comment]
```
$ Code/Quick_Sim.py Machines/6x2-Pavel2 -n6 -r
```

You need to force block size 6 and "recursive" rules (rules which use other rules).

**Comment by sligocki** [comment]
To clarify a bit, Quick_Sim is (well) quick-and-dirty. Most notably with block size. It is attempting to automatically detect the best block size using a heuristic, but that heuristic doesn't always work. You can override the block size explicitly with `-n` and in general, when we did big searches in the past, we tried all block sizes (up to some cutoff) sequentially (not trusting the block finder).

Recursive rules are a somewhat experimental feature in the codebase. I think they are correct, but I have a lot less confidence than the basic rules. So that feature is off by default, but available with the `-r` flag. If Quick_Sim.py isn't working on a TM, it's a good option to try.

**Comment by sligocki** [comment]
I've tweaked the default parameters so that you no longer need to explicitly do `-n6` for this machine. But you will still need the `-r` flag.

**Comment by nickdrozd** [comment]
Nice, works for me!
