### ISSUE TITLE
Machine to handle

### ISSUE THREAD

**Issue by nickdrozd** [sligocki/busy-beaver#5]
Here's one that seems like it could be handled by your simulator:

```
1RB 2LA 1RA  1LA 0LB 2RB
```

Every so often it gets into a configuration just a solid block of 2s:

```
0^inf <A (2) 2^6 0^inf
```

The length of the block extends each time by 2^n. So the numbers are:

- 1 + 2^1 = 3
- 1 + 2^1 + 2^2 = 7
- 1 + 2^1 + 2^2 + 2^3 = 15
- 1 + 2^1 + 2^2 + 2^3 + 2^4= 31
- ...

This is one of the few Christmas tree-like machines left unhandled among the short categories. All the rest are counters.

**Comment by sligocki** [comment]
This one can be proven with block size 2:
```
$ Code/Quick_Sim.py <(echo "1RB 2LA 1RA  1LA 0LB 2RB") -rn2
```

**Comment by nickdrozd** [comment]
Is there any way to get the block finder to detect that automatically?

**Comment by nickdrozd** [comment]
Here's a list of 2/3 machines that whose block size wasn't detected automatically:

```
1RB 0RB 2LA  1LA 2RB 1LB
1RB 1LA 2LA  1LA 2RB 1LB
1RB 1LB 2LA  1LA 2RB 1LB
1RB 1RB 2LA  1LA 2RB 1LB
1RB 2LA 1RA  0LA 2RB 1LB
1RB 2LA 1RA  1LA 0LB 2RB
1RB 2LA 1RA  1LA 1LA 2RB
1RB 2LA 1RA  1LA 1RA 2RB
1RB 2LA 1RA  1LA 1RB 2RB
1RB 2LA 1RA  1LA 2LA 2RB
1RB 2LA 1RA  1LA 2LB 2RB
1RB 2LA 1RA  1LA 2RA 0LB
1RB 2LA 1RA  1LA 2RA 2RB
1RB 2LA 1RA  1LA 2RB 1LB
1RB 2LA 1RA  1LA 2RB 2RB
1RB 2LA 1RA  1LB 2LA 2RB
1RB 2LA 2LA  1LA 2RB 1LB
1RB 2LB 0RA  1LA 2RB 1LB
1RB 2LB 2LA  1LA 2RB 1LB
1RB 2RB 2LA  1LA 2RB 1LB
```

**Comment by sligocki** [comment]
> Is there any way to get the block finder to detect that automatically?

Not that I know of. It's decent ... but not perfect. If you can think up any better way to auto-detect block size, I'd be interested to hear. As it is I find that automatic detection catches a majority of things and then I have to cycle through all block-sizes manually to cleanup the remaining stragglers.

This case is especially tricky because you cannot notice that it needs block size two until you try to prove recursive rules ... I suppose when you get to this case, you could try to reset the block size ...
